fix: create fleet post request
kubeshop/kuskgateway-api-server pull request #48
Opened 2022-05-24 07:51 UTC by mortada-codes

This PR...

## Changes

- create fleet post request definition 

## Fixes

-

## Checklist

- [ ] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

2022-05-24 08:26 UTC, kylehodgetts requested changes

2022-05-24 08:56 UTC, jasmingacic commented on api/openapi.yaml
> +                openapi:
Can an Envoy fleet be created with these params at all?
The only two required fields i can see are https://github.com/kubeshop/kusk-gateway/blob/main/api/v1alpha1/envoyfleet_types.go#L42-L46

2022-05-25 07:32 UTC, mortada-codes commented on api/openapi.yaml
> +                openapi:
the `openapi` field represents this yaml https://github.com/kubeshop/kusk-gateway/blob/main/config/crd/bases/gateway.kusk.io_envoyfleet.yaml
the yaml content contains the required ServiceConfig properties

2022-05-25 10:32 UTC, jasmingacic approved these changes

2022-05-25 10:33 UTC, merged